#!/bin/bash

quiet=false
verbose=false

while getopts :v:q opt ; do
    case $opt in
        v) verbose=true ;;
        q) quiet=true ;;
    esac
done
shift $((OPTIND-1))

tests=${@:-*-test.ps}

command="gs -q -dNOPAUSE -dNODISPLAY -I${0%/*} -dverbose=$verbose $tests quit.ps"
if $quiet ; then
    $command
else
    time $command
fi
